version: '3.9'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: bloglite
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_DB: bloglite
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
