name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: bloglite
          POSTGRES_USER: bloguser
          POSTGRES_PASSWORD: blogpass
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U bloguser -d bloglite"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      POSTGRES_DB: bloglite
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
      POSTGRES_HOST: localhost
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install -r requirements.txt
    - run: python manage.py migrate
    - run: pytest --cov=blog
